---
title: "yosephine_datacleaning"
format: html
editor: visual
---

### Cleaning Data

1.  cc-est2019-alldata-27.csv

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
demographic_all <- read.csv("../data/cc-est2019-alldata-27.csv")
head(demographic_all)
```

```{r}
demographic_all <- demographic_all %>%
  mutate(White = WA_MALE + WA_FEMALE,
         Black = BA_MALE + BA_FEMALE,
         Hispanic = H_MALE + H_FEMALE,
         Indian_Alaska = IA_MALE + IA_FEMALE,
         Asian = AA_MALE + AA_FEMALE,
         Hawaiian_PI = NA_MALE + NA_FEMALE,
         Two_or_more = TOM_MALE + TOM_FEMALE)

demographic_all <- demographic_all %>% 
  select(STATE, COUNTY, CTYNAME, YEAR, TOT_POP, TOT_MALE, TOT_FEMALE, White, Black, Hispanic, Indian_Alaska, Asian, Hawaiian_PI, Two_or_more)

demographic_all
```

### Data Visualization

```{r}
mn_demographic_long <- demographic_all %>%
  select(CTYNAME, White, Black, Hispanic, Indian_Alaska, Asian, Hawaiian_PI, Two_or_more) %>%
  pivot_longer(cols = c(White, Black, Hispanic, Indian_Alaska, Asian, Hawaiian_PI, Two_or_more),
               names_to = "Race",
               values_to = "Population")

# Plot the demographic breakdown for each county
<<<<<<< Updated upstream
ggplot(mn_demographic_long, aes(x = reorder(CTYNAME, -Population), y = Population, fill = Race)) +
=======
ggplot(demographic_all, aes(x = reorder(CTYNAME, -TOT_POP), y = TOT_POP)) +
>>>>>>> Stashed changes
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Demographic Breakdown by Race in Minnesota Counties",
       x = "County",
       y = "Population",
       fill = "Race") +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1))
```

### Next Step?
